Mon Jun 26 12:23:59 2023
Windows-10-10.0.22621
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.04s
Early init took 0.00s
Loader init took 0.02s
Loading error handling took 0.02s
Loading script took 0.23s
Loading save slot metadata. took 0.01s
Loading persistent took 0.00s
Faled to initialize steam: FileNotFoundError("Could not find module 'C:\\Users\\thesh\\Desktop\\renpy-8.0.3-sdk\\lib\\py3-windows-x86_64\\steam_api64.dll' (or one of its dependencies). Try using the full path with constructor syntax.")
Running init code took 0.05s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\thesh\\AppData\\Roaming/RenPy/backups\\Breaking the Ice':
Dump and make backups. took 0.04s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.01s
DPI scale factor: 1.104167
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.46s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.01s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Performance test:
Interface start took 0.17s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 2080/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 536.23'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1714, 964) drawable=(1714, 964)
Maximum texture size: 4096x4096

Full traceback:
  File "game/story/touchdown.rpy", line 120, in script
    p loud "“I can’t quit the raid! My guild will kill me!”"
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 1206, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 1030, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 986, in resolve_say_attributes
    renpy.exports.show(show_image)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\display\transform.py", line 881, in _duplicate
    args.extraneous()
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'phone' does not accept attributes 'loud'.

While running game code:
  File "game/story/touchdown.rpy", line 120, in script
    p loud "“I can’t quit the raid! My guild will kill me!”"
Exception: Image 'phone' does not accept attributes 'loud'.
